/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_crossroads_jni_XSLibrary__ */

#ifndef _Included_io_crossroads_jni_XSLibrary__
#define _Included_io_crossroads_jni_XSLibrary__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_bind
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1bind
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_connect
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1connect
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1errno
  (JNIEnv *, jobject);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_getsockoptInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1getsockoptInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_getsockoptLong
 * Signature: (JIJ)I
 */
JNIEXPORT jlong JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1getsockoptLong
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_getsockoptByte
 * Signature: (JI[B)I
 */
JNIEXPORT jbyteArray JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1getsockoptByte
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1init
  (JNIEnv *, jobject);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_recv
 * Signature: (J[BII)I
 */
JNIEXPORT jbyteArray JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1recv
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_send
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1send
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_setctxoptInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1setctxoptInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_setctxoptLong
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1setctxoptLong
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_setctxoptByte
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1setctxoptByte
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_setsockoptInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1setsockoptInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_setsockoptLong
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1setsockoptLong
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_setsockoptByte
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1setsockoptByte
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_shutdown
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1shutdown
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_socket
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1socket
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_term
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1term
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_version
 * Signature: ([I[I[I)V
 */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1version
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_stopwatch_start
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1stopwatch_1start
  (JNIEnv *, jobject);

/*
 * Class:     io_crossroads_jni_XSLibrary__
 * Method:    xs_stopwatch_stop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1stopwatch_1stop
  (JNIEnv *, jobject, jlong);

    /*
     * Class:     io_crossroads_jni_XSLibrary__
     * Method:    xs_poll
     * Signature: ([Lio/crossroads/jni/xs_pollitem_t;II)I
     */
JNIEXPORT jint JNICALL Java_io_crossroads_jni_XSLibrary_00024_xs_1poll
    (JNIEnv *, jobject, jobjectArray, jint, jint);
    
#ifdef __cplusplus
}
#endif
#endif
